model:
  name: "ViT"
  exp:
    input_dims: 3
  method: "exp"
  output_dims: 3
  height: 192
  width: 384
  encoder_depth: 6
  encoder_embed_dim: 768
  encoder_num_heads: 12
  decoder_depth: 6
  decoder_embed_dim: 512
  decoder_num_heads: 16

data:
  data_path: "./dataset/B"
  grid_path: "./dataset/grid.npy"
  train_size: 0.8
  finetune_size: 0.2
  train_num_list: [0]
  eval_num_list: [0]
  finetune_num_list: [50]
  batch_size: 32
  post_dir: "./postprocessing/visualization/"
  max_value_list: [ 4.6, 1.0, 0.18418664581293126]
  min_value_list: [-2.0, -0.18382872836312403, -0.1839052340212462]
  data_group_size: 50

optimizer:
  epochs: 1000
  lr: 0.0005
  wave_level: 1

ckpt:
  summary_dir: "./summary_dir"
  save_ckpt_interval: 1000
  ckpt_path: "/summary_dir/ckpt_dir/ViT_exp_bs_32-1000_70.ckpt"

eval:
  eval_interval: 10
  plot_interval: 100