name: ms
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cudatoolkit=11.1.1=ha002fc5_10
  - cudnn=8.0.4=cuda11.1_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - icu=67.1=he1b5a44_0
  - kiwisolver=1.4.2=py38h295c915_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py38h06a4308_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h0a891b7_3
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - asttokens==2.0.8
    - astunparse==1.6.3
    - charset-normalizer==2.1.1
    - dill==0.3.5.1
    - docopt==0.6.2
    - idna==3.4
    - mindspore-gpu==1.8.1
    - multiprocess==0.70.13
    - numpy==1.23.3
    - packaging==21.3
    - pandas==1.5.0
    - pathos==0.2.9
    - pillow==9.2.0
    - pipreqs==0.4.11
    - pox==0.3.1
    - ppft==1.7.6.5
    - protobuf==4.21.6
    - psutil==5.9.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - requests==2.28.1
    - salib==1.4.5
    - scipy==1.9.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - yarg==0.1.9
prefix: /home/zhanglulu/data/cd/envs/ms
